# Generated by Django 2.2.14 on 2020-07-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20200705_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resume',
            new_name='upload_your_resume',
        ),
    ]
