# Generated by Django 2.2.14 on 2020-07-07 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200706_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_postings',
            name='job_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
