# Generated by Django 2.2.14 on 2020-07-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20200707_2015'),
        ('web_app', '0008_auto_20200712_0729'),
    ]

    operations = [
    ]
