# Generated by Django 2.2.16 on 2020-09-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20200714_1120'),
        ('web_app', '0010_auto_20200727_0012'),
    ]

    operations = [
    ]
